version: "3.5"


services:
  pgdb:
    image: postgres
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: webapp
    # volumes:
    #   - ./database/data:/var/lib/postgresql/data:rw
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    networks:
      - net
  
  server:
    image: dockerwebapp_server
    # volumes:
    #   - ./server:/usr/src/webapp
    ports:
      - 5555:5555
    depends_on:
      - pgdb
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    networks:
      - net
networks:
  net: