version: "3.5"

services:
  nginx:
    image: "nginx:alpine"
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends:
      - backend
      - web
  backend:
    build: ./server
    # command: python3 manage.py runserver 0.0.0.0:5555
    volumes:
      - ./server:/usr/src/backend
    ports:
      - 5555:5555
  web:
    build: ./web
    command: start
    volumes:
      - ./web:/usr/src/app
    ports:
      - 3000:3000

  # migrate:
  #   build: ./server
  #   command: python3 manage.py migrate
  #   volumes:
  #     - ./server:/usr/src/webapp
  #   depends_on:
  #     - pgdb
