version: "3.5"

services:
  backend:
    build: ./server
    # command: python3 manage.py runserver 0.0.0.0:5555
    volumes:
      - ./server:/usr/src/backend
    ports:
      - 5555:5555
  web:
    build: ./web
    command: start
    volumes:
      - ./web:/usr/src/app
    ports:
      - 3000:3000
  nginx:
    image: "nginx:alpine"
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - web
