# Generated by Django 2.0 on 2018-06-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0001_initial'),
        ('rooms', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='messages',
            field=models.ManyToManyField(through='msgs.UserMessages', to='msgs.Message'),
        ),
        migrations.AddField(
            model_name='user',
            name='rooms',
            field=models.ManyToManyField(through='rooms.UserRooms', to='rooms.Room'),
        ),
    ]
