# Generated by Django 2.0 on 2018-06-25 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomMessages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.Room')),
            ],
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='room',
        ),
        migrations.AddField(
            model_name='roommessages',
            name='room_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.GroupMessage'),
        ),
        migrations.AddField(
            model_name='room',
            name='messages',
            field=models.ManyToManyField(through='rooms.RoomMessages', to='rooms.GroupMessage'),
        ),
    ]
