# Generated by Django 2.0 on 2018-06-25 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommessages',
            name='from_user',
        ),
    ]
